document.writeln('  <header class="blog-header py-3">');  
document.writeln('    <div class="row flex-nowrap justify-content-between align-items-center">');  
document.writeln('      <div class="col-4 pt-1">');  
document.writeln('        <a class="link-secondary" href="#"></a>');  
document.writeln('      </div>');  
document.writeln('      <div class="col-4 text-center">');  
document.writeln('        <a class="blog-header-logo text-dark" href="#">VISHCI LAB</a>');  
document.writeln('      </div>');  
document.writeln('      <div class="col-4 d-flex justify-content-end align-items-center">');  
document.writeln('        <a class="link-secondary" href="#" aria-label="Search">');  
document.writeln('          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>');  
document.writeln('        </a>');  
document.writeln('        <a class="link-secondary" href="#"></a>');  
document.writeln('      </div>');  
document.writeln('    </div>');  
document.writeln('  </header>');  
document.writeln('  <div class="nav-scroller py-1 mb-2">');  
document.writeln('    <nav class="nav d-flex justify-content-between">');  
document.writeln('      <a class="p-2 link-secondary" href="https://hcilabxjtlu.github.io/homepage/index.html">Index</a>');  
//document.writeln('      <a class="p-2 link-secondary" href="https://hcilabxjtlu.github.io/homepage/blogs.html">Blogs</a>');  
document.writeln('      <a class="p-2 link-secondary" href="https://hcilabxjtlu.github.io/homepage/publications.html">Publications</a>');  
document.writeln('      <a class="p-2 link-secondary" href="https://hcilabxjtlu.github.io/homepage/members.html">Members</a>');  
document.writeln('      <a class="p-2 link-secondary" href="https://hcilabxjtlu.github.io/homepage/contactus.html">Contact Us</a>');  
document.writeln('    </nav>');  
document.writeln('  </div>');  
