document.writeln('    <div class="col-md-4">');  
document.writeln('      <div class="position-sticky" style="top: 2rem;">');  
document.writeln('        <div class="p-4 mb-3 bg-light rounded">');  
document.writeln('          <h4 class="fst-italic">Guide</h4>');  
document.writeln('          <ol class="list-unstyled mb-0">'); 
document.writeln('            <li><a href="https://hcilabxjtlu.github.io/homepage/meetingschedule.html">Group Meeting Schedule</a></li>'); 
document.writeln('          </ol>'); 
document.writeln('        </div>');  
document.writeln('        <div class="p-4">');  
document.writeln('          <h4 class="fst-italic">Tab</h4>');  
document.writeln('          <ol class="list-unstyled mb-0">');  
document.writeln('            <li><a href="visualization.html">Visualization</a></li>');  
document.writeln('            <li><a href="arvr.html">AR/VR</a></li>');  
document.writeln('            <li><a href="storytelling.html">Storytelling</a></li>');  
document.writeln('            <li><a href="ml.html">Machine Learning</a></li>');  
document.writeln('          </ol>');  
document.writeln('        </div>');  
document.writeln('        <div class="p-4">');  
document.writeln('          <h4 class="fst-italic">Archives</h4>');  
document.writeln('          <ol class="list-unstyled mb-0">');  
document.writeln('            <li><a href="september2021.html">September 2021</a></li>');  
document.writeln('            <li><a href="august2021.html">August 2021</a></li>');  
document.writeln('          </ol>');  
document.writeln('        </div>');  
document.writeln('      </div>');  
document.writeln('    </div>');  
